myStr ="hello world"

print("mi primer " + myStr)
print(f"my name is {myStr}")
print("My name is {0}".format(myStr))

# print(dir(myStr))

# print(myStr.upper())
# print(myStr.lower())
# print(myStr.swapcase())
# print(myStr.capitalize())
# print(myStr.replace('hello','bye').upper())
# print(myStr.count(' '))
# print(myStr.startswith('hola'))
# print(myStr.endswith('world'))
# print(myStr.split())
# print(myStr.find('o'))
# print(len(myStr))
# print(myStr.index('e'))
# print(myStr.isnumeric())
# print(myStr.isalpha())
# print(myStr[0])
# print(myStr[3])
# print(myStr[4])
# print(myStr[-1])